### ISSUE TITLE
Day-2

### ISSUE THREAD

**Issue by marijadjurisic** [marijadjurisic/airvironment-frontend-summer#1]

**Comment by marijadjurisic** [comment]
- [x] Install Prettier #2
- [x] Install node-sass #4
- [x] Adjust general app params #5
- [x] Create Home page #6
- [x] Format code according to prettier #8
