### ISSUE TITLE
Day-7

### ISSUE THREAD

**Issue by marijadjurisic** [marijadjurisic/airvironment-frontend-summer#35]

**Comment by marijadjurisic** [comment]
- [x] Create filter component #37
- [x] Add functionality to Filter component #40
- [x] Adjust style for Filter component #42
- [x] The Average page is displaying data from previous state #44
- [x] Change initial state for measurements reducer #45
